import { tool } from "@opencode-ai/plugin"
import type { Shell } from "@opencode-ai/plugin"

/**
 * TDD Init Tool
 *
 * Initializes the TDD project structure:
 * - .context/ - Foundational documents (PRD, spec, test spec, agent spec)
 * - .tdd/ - Workflow state (gitignored)
 * - tasks/ - Individual TDD task files
 */
export const tddInitTool = ($: Shell, directory: string) =>
  tool({
    description: `Initialize TDD project structure with .context/, .tdd/, and tasks/ directories.
Creates initial state.json for workflow tracking.
Safe to run multiple times - won't overwrite existing files.`,
    args: {
      projectType: tool.schema
        .enum(["node", "python", "go", "rust", "generic"])
        .optional()
        .describe("Project type for test command defaults"),
      force: tool.schema
        .boolean()
        .optional()
        .describe("Force re-initialization (resets state)"),
    },
    async execute(args) {
      const { projectType = "node", force = false } = args

      try {
        // Create directories
        await $`mkdir -p ${directory}/.context`
        await $`mkdir -p ${directory}/.tdd`
        await $`mkdir -p ${directory}/tasks`

        // Add .tdd to .gitignore if not already there
        try {
          const gitignore = await $`cat ${directory}/.gitignore 2>/dev/null`.text()
          if (!gitignore.includes(".tdd/")) {
            await $`echo "\n# TDD workflow state (auto-generated)\n.tdd/" >> ${directory}/.gitignore`
          }
        } catch {
          // No .gitignore exists, create one
          await $`echo "# TDD workflow state (auto-generated)\n.tdd/" > ${directory}/.gitignore`
        }

        // Determine test command based on project type
        const testCommands: Record<string, string> = {
          node: "npm test",
          python: "pytest",
          go: "go test ./...",
          rust: "cargo test",
          generic: "make test",
        }

        // Check if state already exists
        let stateExists = false
        try {
          await $`test -f ${directory}/.tdd/state.json`
          stateExists = true
        } catch {
          stateExists = false
        }

        if (stateExists && !force) {
          return `TDD structure already initialized.

Existing directories:
- .context/ - Foundational documents
- .tdd/ - Workflow state
- tasks/ - Task files

Use force=true to reset state.

Run \`tdd_status\` to check current progress.`
        }

        // Create initial state
        const initialState = {
          version: "1.0.0",
          project_type: projectType,
          test_command: testCommands[projectType],
          workflow_phase: "not_started",
          current_task: null,
          current_attempt: 0,
          completed_tasks: [],
          failed_tasks: [],
          total_tasks: 0,
          last_critic_feedback: null,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }

        await $`echo ${JSON.stringify(initialState, null, 2)} > ${directory}/.tdd/state.json`

        // Create test mapping file
        const testMapping = {
          version: "1.0.0",
          mappings: {},
        }
        await $`echo ${JSON.stringify(testMapping, null, 2)} > ${directory}/.tdd/test-mapping.json`

        // Create placeholder files in .context if they don't exist
        const contextFiles = [
          { name: "prd.md", content: "# Product Requirements Document\n\n<!-- Generated by /architect-prd or /architect-full -->\n" },
          { name: "spec.md", content: "# Technical Specification\n\n<!-- Generated by /architect-spec or /architect-full -->\n" },
          { name: "test.md", content: "# Test Specification\n\n<!-- Generated by /architect-tests or /architect-full -->\n" },
          { name: "agent-spec.md", content: "# Agent Specification\n\n<!-- Abstract principles for AI agents - generated by /architect-full -->\n" },
        ]

        for (const file of contextFiles) {
          try {
            await $`test -f ${directory}/.context/${file.name}`
            // File exists, don't overwrite
          } catch {
            // File doesn't exist, create placeholder
            await $`echo ${file.content} > ${directory}/.context/${file.name}`
          }
        }

        return `✅ TDD project initialized successfully!

## Created Structure

\`\`\`
${directory}/
├── .context/
│   ├── prd.md          # Product requirements
│   ├── spec.md         # Technical specification
│   ├── test.md         # Test specification
│   └── agent-spec.md   # Agent principles
├── .tdd/
│   ├── state.json      # Workflow state
│   └── test-mapping.json
├── tasks/              # TDD task files go here
└── .gitignore          # Updated to ignore .tdd/
\`\`\`

## Project Settings

- **Type**: ${projectType}
- **Test Command**: ${testCommands[projectType]}

## Next Steps

1. Generate foundational documents:
   \`/architect-full "Your project description"\`

2. Or create documents individually:
   - \`/architect-prd\` - Product requirements
   - \`/architect-spec\` - Technical specification
   - \`/architect-tests\` - Test specification

3. Once documents are ready, start TDD:
   \`/tdd-start\``
      } catch (error) {
        return `❌ Failed to initialize TDD structure: ${error}`
      }
    },
  })
