import { tool } from "@opencode-ai/plugin"
import type { Shell } from "@opencode-ai/plugin"

/**
 * TDD Init Tool
 *
 * Initializes the TDD project structure:
 * - .context/ - Foundational documents (PRD, spec, test spec, agent spec)
 * - .tdd/ - Workflow state (gitignored)
 * - tasks/ - Individual TDD task files
 */
export const tddInitTool = ($: Shell, directory: any) =>
  tool({
    description: `Initialize TDD project structure with .context/, .tdd/, and tasks/ directories.
Creates initial state.json for workflow tracking.
Safe to run multiple times - won't overwrite existing files.`,
    args: {
      projectType: tool.schema
        .enum(["node", "python", "go", "rust", "generic"])
        .optional()
        .describe("Project type for test command defaults"),
      force: tool.schema
        .boolean()
        .optional()
        .describe("Force re-initialization (resets state)"),
    },
    async execute(args) {
      const { projectType = "node", force = false } = args

      // Handle directory in various formats
      const dir = typeof directory === "string"
        ? directory
        : (directory?.path || process.cwd())

      try {
        // Create directories
        await $`mkdir -p ${dir}/.context`
        await $`mkdir -p ${dir}/.tdd`
        await $`mkdir -p ${dir}/tasks`

        // Add .tdd to .gitignore if not already there
        try {
          const gitignore = await $`cat ${dir}/.gitignore 2>/dev/null`.text()
          if (!gitignore.includes(".tdd/")) {
            await $`echo "\n# TDD workflow state (auto-generated)\n.tdd/" >> ${dir}/.gitignore`
          }
        } catch {
          // No .gitignore exists, create one
          await $`echo "# TDD workflow state (auto-generated)\n.tdd/" > ${dir}/.gitignore`
        }

        // Determine test command based on project type
        const testCommands: Record<string, string> = {
          node: "npm test",
          python: "pytest",
          go: "go test ./...",
          rust: "cargo test",
          generic: "make test",
        }

        // Check if state already exists
        let stateExists = false
        try {
          await $`test -f ${dir}/.tdd/state.json`
          stateExists = true
        } catch {
          stateExists = false
        }

        if (stateExists && !force) {
          return `TDD structure already initialized.

Existing directories:
- .context/ - Foundational documents
- .tdd/ - Workflow state
- tasks/ - Task files

Use force=true to reset state.

Run \`tdd_status\` to check current progress.`
        }

        // Create initial state
        const initialState = {
          version: "1.0.0",
          project_type: projectType,
          test_command: testCommands[projectType],
          workflow_phase: "not_started",
          current_task: null,
          current_attempt: 0,
          completed_tasks: [],
          failed_tasks: [],
          total_tasks: 0,
          last_critic_feedback: null,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }

        await $`echo ${JSON.stringify(initialState, null, 2)} > ${dir}/.tdd/state.json`

        // Create test mapping file
        const testMapping = {
          version: "1.0.0",
          mappings: {},
        }
        await $`echo ${JSON.stringify(testMapping, null, 2)} > ${dir}/.tdd/test-mapping.json`

        // Create placeholder files in .context if they don't exist
        const contextFiles = [
          { name: "prd.md", content: "# Product Requirements Document\n\n<!-- Generated by /tdd/prd or /tdd/architect-full -->\n" },
          { name: "agent-spec.md", content: "# Agent Specification\n\n<!-- Generated by /tdd/agent-spec or /tdd/architect-full -->\n" },
        ]

        for (const file of contextFiles) {
          try {
            await $`test -f ${dir}/.context/${file.name}`
            // File exists, don't overwrite
          } catch {
            // File doesn't exist, create placeholder
            await $`echo ${file.content} > ${dir}/.context/${file.name}`
          }
        }

        // Create spec/ directory with README placeholder
        try {
          await $`test -d ${dir}/.context/spec`
          // Directory exists
        } catch {
          // Create spec directory and README
          await $`mkdir -p ${dir}/.context/spec`
          const specReadme = "# Technical Specification\n\n<!-- Generated by /tdd/spec or /tdd/architect-full -->\n\nSee individual numbered files in this directory for complete technical documentation.\n"
          await $`echo ${specReadme} > ${dir}/.context/spec/README.md`
        }

        // Create test/ directory with README placeholder
        try {
          await $`test -d ${dir}/.context/test`
          // Directory exists
        } catch {
          // Create test directory and README
          await $`mkdir -p ${dir}/.context/test`
          const testReadme = "# Test Specification\n\n<!-- Generated by /tdd/test-spec or /tdd/architect-full -->\n\nSee individual numbered files in this directory for complete test documentation.\n"
          await $`echo ${testReadme} > ${dir}/.context/test/README.md`
        }

        return `✅ TDD project initialized successfully!

## Created Structure

\`\`\`
${dir}/
├── .context/
│   ├── prd.md          # Product requirements
│   ├── spec/           # Technical specification (numbered files)
│   │   └── README.md   # Spec roadmap
│   ├── test/           # Test specification (numbered files)
│   │   └── README.md   # Test roadmap
│   └── agent-spec.md   # Agent principles
├── .tdd/
│   ├── state.json      # Workflow state
│   └── test-mapping.json
├── tasks/              # TDD task files go here
└── .gitignore          # Updated to ignore .tdd/
\`\`\`

## Project Settings

- **Type**: ${projectType}
- **Test Command**: ${testCommands[projectType]}

## Next Steps

**Option 1: Iterative (Recommended)**
Review and refine each document:
1. \`/tdd/prd "Your project description"\` - Generate PRD → Review
2. \`/tdd/spec\` - Generate tech spec → Review
3. \`/tdd/test-spec\` - Generate test spec → Review
4. \`/tdd/agent-spec\` - Generate agent principles → Review
5. \`/tdd/tasks\` - Generate task files → Review
6. \`/tdd/start\` - Begin implementation

**Option 2: All at Once**
\`/tdd/architect-full "Your project description"\`

**Option 3: Manual**
Create docs in .context/ and tasks/ manually`
      } catch (error) {
        return `❌ Failed to initialize TDD structure: ${error}`
      }
    },
  })
